# Generated by Django 5.2.1 on 2025-05-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='Untitled Product', max_length=200),
        ),
    ]
